spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/finance_db
    username: finance_user
    password: finance_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: Finance-Manager
server:
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: strict
  port: 8080
jwt:
  secretKey: 46b222a7653e3f71f6979af8399875bf