spring:
  datasource:
    url: jdbc:h2:mem:finance_db
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: Finance-Manager
server:
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: strict
  port: 8080
jwt:
  secretKey: 46b222a7653e3f71f6979af8399875bf